### PR TITLE
BookNowModal Feature: Create a responsive NavigationStep atom component

### PR DESCRIPTION
**Pull request by matr1xb0ss**
In scope of this PR responsive NavigationStep atom component was created.
In the next PR it will be utilised to create a NavigationStepsPanel molecule component.
Have a look:

### CODE REVIEW

**Comment by maximalvido** [comment]
Is indentation configured properly? I think it's like 8 spaces there per tab, I am seeing 4 spaces per tab in the other FE files. @matr1xb0ss

**Comment by spencermarx** [comment]
Yeah no idea what prettier/spacing tule we have in place (if any). Would love to have that hard standardized though 👍

**Comment by matr1xb0ss** [comment]
@spencermarx @maximalvido 
That's a valid concern guys, In the moment of PR creation I though about it.
My IDEA says: 'Tab Size: 4'

tab

Also is it only for me or the other files has the same spacing?
Have a look:
https://github.com/Aclarify/beantown/blob/main/beantown-website/components/atoms/button.atom.tsx

file

**Comment by maximalvido** [comment]
I would configure it qith 4 spaces and run eslint in another xommand, @spencermarx do you want us to fix that in the whole code?

**Comment by spencermarx** [comment]
That would be phenomenal. I have no space/tab quantity preference, as long as it’s consistent. 

It would be awesome if we could have a separate PR with the result of running lint across the whole repo 👍

**Comment by matr1xb0ss** [comment]
@spencermarx @maximalvido 
I've changed a prettier configuration to use spaces instead of tabs and run prettier on navigation-step.atom file.
Please have a look.

Will run prettier on whole beantown-website folder in scope of separate PR.

**Review by rtanchak — APPROVED** [review]

**Pull request merged**
